// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  Options as ClientOptions,
  TDataShape,
} from "@hey-api/client-fetch";
import { client as _heyApiClient } from "./client.gen";
import type {
  CreateMessageData,
  CreateMessageError,
  CreateMessageResponse,
  CreateTokenData,
  CreateTokenResponse,
  DeleteChatData,
  DeleteChatError,
  DeleteChatResponse,
  ListChatsData,
  ListChatsResponse,
  ReadChatData,
  ReadChatError,
  ReadChatResponse,
  UpdateChatData,
  UpdateChatError,
  UpdateChatResponse,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Create Token
 */
export const createToken = <ThrowOnError extends boolean = false>(
  options?: Options<CreateTokenData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    CreateTokenResponse,
    unknown,
    ThrowOnError
  >({
    url: "/api/auth/token",
    ...options,
  });
};

/**
 * List Chats
 */
export const listChats = <ThrowOnError extends boolean = false>(
  options?: Options<ListChatsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListChatsResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/chats/",
    ...options,
  });
};

/**
 * Delete Chat
 */
export const deleteChat = <ThrowOnError extends boolean = false>(
  options: Options<DeleteChatData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChatResponse,
    DeleteChatError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/chats/{chat_id}",
    ...options,
  });
};

/**
 * Read Chat
 */
export const readChat = <ThrowOnError extends boolean = false>(
  options: Options<ReadChatData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ReadChatResponse,
    ReadChatError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/chats/{chat_id}",
    ...options,
  });
};

/**
 * Update Chat
 */
export const updateChat = <ThrowOnError extends boolean = false>(
  options: Options<UpdateChatData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateChatResponse,
    UpdateChatError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/chats/{chat_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Create Message
 */
export const createMessage = <ThrowOnError extends boolean = false>(
  options: Options<CreateMessageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateMessageResponse,
    CreateMessageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/chats/{chat_id}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};
