// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * ChatRequest
 */
export type ChatRequest = {
  /**
   * Messages
   */
  messages: Array<Message>;
  /**
   * Model
   */
  model: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
  /**
   * Role
   */
  role: "user" | "assistant";
  /**
   * Content
   */
  content: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type CreateMessageData = {
  body: ChatRequest;
  path?: never;
  query?: never;
  url: "/api/chat";
};

export type CreateMessageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMessageError = CreateMessageErrors[keyof CreateMessageErrors];

export type CreateMessageResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
