// This file is auto-generated by @hey-api/openapi-ts

export type ChatRequest = {
  messages: Array<Message>;
  model: string;
};

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

export type Message = {
  role: "user" | "assistant";
  content: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type CreateMessageData = {
  body: ChatRequest;
  path?: never;
  query?: never;
  url: "/api/chat";
};

export type CreateMessageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMessageError = CreateMessageErrors[keyof CreateMessageErrors];

export type CreateMessageResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};
