"""Make embedding nullable

Revision ID: 262ff3004f7c
Revises: 5de3e38b7091
Create Date: 2025-10-10 15:19:12.347856

"""

from typing import Sequence, Union

import pgvector.sqlalchemy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "262ff3004f7c"
down_revision: Union[str, None] = "5de3e38b7091"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunk",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunk",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=False,
    )
    # ### end Alembic commands ###
