"""remove_user_id_from_chat

Revision ID: 342fe082d552
Revises: ee1555c16f6c
Create Date: 2025-09-06 05:24:42.956665

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "342fe082d552"
down_revision: Union[str, None] = "ee1555c16f6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
    )
    op.drop_index(op.f("ix_chat_user_id"), table_name="chat")
    op.drop_column("chat", "user_id")
    op.create_index(op.f("ix_document_url"), "document", ["url"], unique=False)
    op.alter_column(
        "document_chunk",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunk",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=True,
    )
    op.drop_index(op.f("ix_document_url"), table_name="document")
    op.add_column(
        "chat", sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_index(op.f("ix_chat_user_id"), "chat", ["user_id"], unique=False)
    op.alter_column(
        "chat",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###
