"""add date to decision table unique constraint

Revision ID: 4c21178e7771
Revises: e3d01afb9bab
Create Date: 2026-02-27 09:24:15.574282

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c21178e7771"
down_revision: Union[str, None] = "e3d01afb9bab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("decision_spider_number_key"), "decision", type_="unique")
    op.create_unique_constraint(None, "decision", ["spider", "number", "date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "decision", type_="unique")
    op.create_unique_constraint(
        op.f("decision_spider_number_key"),
        "decision",
        ["spider", "number"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
