"""remove document is active and update at

Revision ID: 5de3e38b7091
Revises: 6295567676a8
Create Date: 2025-10-10 15:04:14.196237

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5de3e38b7091"
down_revision: Union[str, None] = "6295567676a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_is_active"), table_name="document")
    op.drop_index(op.f("ix_document_updated_at"), table_name="document")
    op.drop_column("document", "updated_at")
    op.drop_column("document", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "document",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_document_updated_at"), "document", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_document_is_active"), "document", ["is_active"], unique=False
    )
    # ### end Alembic commands ###
