"""drop chat status column

Revision ID: 74487ab86eeb
Revises: 3ff444d68d2a
Create Date: 2025-09-20 17:44:34.495308

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74487ab86eeb"
down_revision: Union[str, None] = "3ff444d68d2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_status", table_name="chat")
    op.drop_column("chat", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type if it doesn't exist
    chatstatus_enum = postgresql.ENUM(
        "PENDING", "IN_PROGRESS", "COMPLETED", name="chatstatus"
    )
    chatstatus_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "chat",
        sa.Column(
            "status",
            chatstatus_enum,
            server_default=sa.text("'COMPLETED'::chatstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index("ix_chat_status", "chat", ["status"], unique=False)
    # ### end Alembic commands ###
