"""add document is active

Revision ID: 98db31e1cc9f
Revises: 74487ab86eeb
Create Date: 2025-10-05 09:43:02.212824

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98db31e1cc9f"
down_revision: Union[str, None] = "74487ab86eeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_index(
        op.f("ix_document_is_active"), "document", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_is_active"), table_name="document")
    op.drop_column("document", "is_active")
    # ### end Alembic commands ###
