"""add full-text search to document_chunk

Revision ID: ce68a9015a46
Revises: 262ff3004f7c
Create Date: 2025-10-18 10:02:22.969158

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce68a9015a46"
down_revision: Union[str, None] = "262ff3004f7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunk",
        sa.Column(
            "text_search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', text)", persisted=True),
            nullable=True,
        ),
    )
    op.create_index(
        "idx_text_search_vector",
        "document_chunk",
        ["text_search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_text_search_vector", table_name="document_chunk", postgresql_using="gin"
    )
    op.drop_column("document_chunk", "text_search_vector")
    # ### end Alembic commands ###
