"""replace decision_sync_state with decision_file

Revision ID: d116fa99952b
Revises: 9f0d4ce7ed40
Create Date: 2026-02-26 11:35:43.883700

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d116fa99952b"
down_revision: Union[str, None] = "9f0d4ce7ed40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_file",
        sa.Column("file", sa.String(), nullable=False),
        sa.Column("spider", sa.String(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column("decision_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["decision_id"], ["decision.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("file"),
    )
    op.create_index(
        op.f("ix_decision_file_spider"), "decision_file", ["spider"], unique=False
    )
    op.drop_table("decision_sync_state")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_sync_state",
        sa.Column("spider", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "last_job_sequence", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("spider", name=op.f("decision_sync_state_pkey")),
    )
    op.drop_index(op.f("ix_decision_file_spider"), table_name="decision_file")
    op.drop_table("decision_file")
    # ### end Alembic commands ###
