"""Add external_id and validity fields to document

Revision ID: e2ad9d2ee899
Revises: 74487ab86eeb
Create Date: 2025-10-06 12:08:27.233112

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2ad9d2ee899"
down_revision: Union[str, None] = "74487ab86eeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("external_id", sa.String(), nullable=True))
    op.add_column(
        "document", sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "document", sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_document_external_id"), "document", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_valid_from"), "document", ["valid_from"], unique=False
    )
    op.create_index(
        op.f("ix_document_valid_to"), "document", ["valid_to"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_valid_to"), table_name="document")
    op.drop_index(op.f("ix_document_valid_from"), table_name="document")
    op.drop_index(op.f("ix_document_external_id"), table_name="document")
    op.drop_column("document", "valid_to")
    op.drop_column("document", "valid_from")
    op.drop_column("document", "external_id")
    # ### end Alembic commands ###
