// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { CreateTokenData, CreateTokenResponse, ReadUserData, ReadUserResponse, ReadLimitsData } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create Token
 */
export const createToken = <ThrowOnError extends boolean = false>(options?: Options<CreateTokenData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateTokenResponse, unknown, ThrowOnError>({
        url: '/api/token',
        ...options
    });
};

/**
 * Read User
 */
export const readUser = <ThrowOnError extends boolean = false>(options?: Options<ReadUserData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ReadUserResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/user',
        ...options
    });
};

/**
 * Read Limits
 */
export const readLimits = <ThrowOnError extends boolean = false>(options?: Options<ReadLimitsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/limits',
        ...options
    });
};