// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { CreateTokenData, CreateTokenResponse, ReadChatData, ReadChatResponse, ReadChatError, CreateMessageData, CreateMessageResponse, CreateMessageError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create Token
 */
export const createToken = <ThrowOnError extends boolean = false>(options?: Options<CreateTokenData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateTokenResponse, unknown, ThrowOnError>({
        url: '/api/auth/token',
        ...options
    });
};

/**
 * Read Chat
 */
export const readChat = <ThrowOnError extends boolean = false>(options: Options<ReadChatData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadChatResponse, ReadChatError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/chats/{chat_id}',
        ...options
    });
};

/**
 * Create Message
 */
export const createMessage = <ThrowOnError extends boolean = false>(options: Options<CreateMessageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateMessageResponse, CreateMessageError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/chats{chat_id}/messages',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};