// This file is auto-generated by @hey-api/openapi-ts

export type Token = {
    access_token: string;
};

export type User = {
    user_id: string;
};

export type CreateTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/token';
};

export type CreateTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type CreateTokenResponse = CreateTokenResponses[keyof CreateTokenResponses];

export type ReadUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type ReadUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type ReadUserResponse = ReadUserResponses[keyof ReadUserResponses];

export type ReadLimitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/limits';
};

export type ReadLimitsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};