// This file is auto-generated by @hey-api/openapi-ts

export type ChatResponse = {
    id?: string;
    messages?: Array<MessageResponse>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type MessageResponse = {
    role: string;
    content: string;
};

export type Token = {
    access_token: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type CreateTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/token';
};

export type CreateTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type CreateTokenResponse = CreateTokenResponses[keyof CreateTokenResponses];

export type ReadChatData = {
    body?: never;
    path: {
        chat_id: string;
    };
    query?: never;
    url: '/api/chat/{chat_id}';
};

export type ReadChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadChatError = ReadChatErrors[keyof ReadChatErrors];

export type ReadChatResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ReadChatResponse = ReadChatResponses[keyof ReadChatResponses];

export type CreateMessageData = {
    body?: never;
    path: {
        chat_id: string;
    };
    query?: never;
    url: '/api/chat/{chat_id}/messages';
};

export type CreateMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMessageError = CreateMessageErrors[keyof CreateMessageErrors];

export type CreateMessageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadLimitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/limits';
};

export type ReadLimitsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};