// This file is auto-generated by @hey-api/openapi-ts

export type ChatResponse = {
    id: string;
    title: string | null;
    messages: Array<MessageResponse>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type MessageRequest = {
    id: string;
    content: string;
};

export type MessageResponse = {
    id: string;
    role: string;
    content: string;
};

export type TokenResponse = {
    access_token: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type CreateTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/token';
};

export type CreateTokenResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type CreateTokenResponse = CreateTokenResponses[keyof CreateTokenResponses];

export type ReadChatData = {
    body?: never;
    path: {
        chat_id: string;
    };
    query?: never;
    url: '/api/chats/{chat_id}';
};

export type ReadChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadChatError = ReadChatErrors[keyof ReadChatErrors];

export type ReadChatResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ReadChatResponse = ReadChatResponses[keyof ReadChatResponses];

export type CreateMessageData = {
    body: MessageRequest;
    path: {
        chat_id: string;
    };
    query?: never;
    url: '/api/chats/{chat_id}/messages';
};

export type CreateMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMessageError = CreateMessageErrors[keyof CreateMessageErrors];

export type CreateMessageResponses = {
    /**
     * Event stream
     */
    200: Blob | File;
};

export type CreateMessageResponse = CreateMessageResponses[keyof CreateMessageResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};